name:                Autoref
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/Autoref#readme
license:             BSD-3-Clause
author:              Stella
maintainer:          example@example.com
copyright:           2024 Stella
category:            Web
extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
  - base >= 4.7 && < 5
  - cassava
  - vector
  - bytestring
  - ghc
  - utility-ht

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  Autoref:
    source-dirs:      src
    main:             Main.hs
